name = "horof-sync"
main = "src/index.js"
compatibility_date = "2026-02-19"
workers_dev = true

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]
